name: My Second Pipeline

on:
  push:
    branches:
      - main
      - feature-login

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hello
        run: |
          echo "Hello Akshara 🚀"
          echo "Listing files:"
          ls -la

  hi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Custom Script
        run: ./script.sh

  deploy:
    needs: [hello, hi]
    runs-on: ubuntu-latest
    environment: production   # 👈 THIS is the magic line

    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to production"
